[package]
name = "sklearn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "5.0.1"
arff = "0.3.0"
polars = "0.40.0"
curl = "0.4.46"
serde_json = "1.0.1"